import Nav from "@components/Nav";
import { Inter } from "next/font/google";

// layout will appear in every route
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="main">
          <div className="gradient" />
        </div>

        <main className="app">
          <Nav />

          {children}
          
        </main>
      </body>
    </html>
  );
}
